
# Inclui o arquivo de cores externo
include colors.conf

# Configurações de texto



window_padding_width      10

background_opacity        0.8
background_blur_radius      5
background_blur_passes      2

scrollback_indicator_opacity       0.0



